version: '3.5'

services:
  backend:
    image: docker_backend_28
    container_name: backend
    ports:
      - 8000:8000
    expose:
      - 8000
    environment:
      REDIS: redis
      DB_USERNAME: postgres
      DB_PASSWORD: example
      DB_HOST: pgsql
    networks:
      - database-network
      - nginx-network
    depends_on:
      - pgsql
    links:
      - pgsql
  frontend:
    image: docker_frontend_28
    container_name: frontend
    ports:
      - 5000:5000
    expose:
      - 5000
    networks:
      - nginx-network
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend
    networks:
      - nginx-network
  redis:
    image: redis
    container_name: redis
    expose:
      - 6379
    ports:
      - 6379:6379
    networks:
      - database-network
  pgsql:
    image: postgres
    container_name: postgresql
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
    networks:
      - database-network
    volumes:
      - ./database:/var/lib/postgresql/data

networks:
  database-network:
    name: db-network  
  nginx-network:
    name: nginx-network  

volumes:
  database:


